# Generated by Django 4.0.4 on 2022-04-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLQuestionsweroptionblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Answeroptionsblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_answer_options', models.TextField(verbose_name='Вариант ответа')),
                ('encoding_answer_options', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кодировка')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'Управление ответами и вариантностью',
            },
        ),
        migrations.CreateModel(
            name='QuestionApiblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_qust', models.IntegerField(verbose_name='Номер вопроса')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Управление вопросами в форме',
            },
        ),
        migrations.CreateModel(
            name='Questionblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Добавление вопроса формы',
            },
        ),
        migrations.CreateModel(
            name='Questionsweroptionblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_title_answer_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcabry.answeroptionsblock', verbose_name='Вариант ответа')),
                ('id_title_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcabry.questionapiblock', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'пункт',
                'verbose_name_plural': 'Управление связями и логикой проекта',
            },
        ),
        migrations.AddField(
            model_name='questionapiblock',
            name='id_api_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcabry.questionblock', verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='Qstionsweblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcabry.questionsweroptionblock', verbose_name='Вопрос')),
                ('id_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcabry.allquestionsweroptionblock', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'Связь и ключ | Шаг',
            },
        ),
        migrations.AddField(
            model_name='allquestionsweroptionblock',
            name='id_title_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcabry.answeroptionsblock', verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='allquestionsweroptionblock',
            name='id_title_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcabry.questionapiblock', verbose_name='Вопрос'),
        ),
    ]
